version: '3.8'

services:
  # React 应用构建服务
  react-app:
    build:
      context: .  # 假设Dockerfile在项目根目录
      dockerfile: Dockerfile
    image: react-app:latest
    environment:
      - NODE_ENV=production
    volumes:
      - ./build:/app/build  # 挂载构建输出目录
    # 这个服务只用于构建，构建完成后就退出
    command: sh -c "npm run build && cp -r build /app/build"

  # Nginx 服务
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"  # 映射主机80端口到容器80端口
    volumes:
      - ./build:/usr/share/nginx/html  # 使用react-app构建的输出
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # 自定义Nginx配置
    depends_on:
      - react-app
    restart: unless-stopped